version: 2
jobs:
  build: #単体テストを実行するジョブ
    working_directory: /root
    docker:
      - image: ruby:2.4.0
    steps:
      - checkout
  deploy: #デプロイするジョブ
    working_directory: /root
    steps:
      - checkout
      - run: cp /root/index.html /

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy: # deployはbuildのあとに実行
          requires:
            - build
          filters: # masterブランチの場合のみデプロイする
            branches:
              only: master
